version: '3.8'
 
services:
  postgres:
    image: postgres:latest
    container_name: mbsys
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: hMXgMezvnA2WyKp
      POSTGRES_DB: mbsys
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
 
volumes:
  db_data:
 